### ISSUE TITLE
Site kickstarter supports newer Typo3 version than supported by it's dependencies

### ISSUE THREAD

**Issue by neil-h** [FluidTYPO3/site#17]
On the "Get preconfigured distribution" screen, FluidTYPO3 site kickstarter says it will work with versions 6.2.0 - 7.5.99, but when attempting to install on 7.5.x, a bunch of errors come up as:
- flux
- fluidcontent
- fluidpages
- builder
- fluidcontent_core

all only support up to 7.4.99.

**Comment by NamelessCoder** [comment]
Hi Neil,

This is true - the "site" extension is just a wrapper that allows you to install on any TYPO3 version (via extension manager or composer alike) and TYPO3 then attempts to resolve the further dependencies. It does that either by suggesting a version that *does* work on the TYPO3 version you run and works with all dependencies; or, as it happens to you, it warns that no appropriate versions can be found for your TYPO3 version.

You, as site administrator, should then get the option to ignore these version requirements which (at the time of writing this) is perfectly safe to do.

The reason is that we haven't yet created releases that are formally compatible with TYPO3 7.5.0. It's not always we have the time required right around the time when new TYPO3 releases are made but always try to make sure in advance that you can ignore the version constraints (because we build in compatibility based on the TYPO3 master branch as well as most recent release and most recent LTS). Although it *would* be much, much easier for us to just raise the maximum supported TYPO3 version to one higher than current version, doing that only results in the extension repository upload failing with a "no supported TYPO3 version defined". So we're kind of stuck with this, with some expected waiting time until formal compatibility, at least for a while still.

**Comment by neil-h** [comment]
Makes sense. Thank you.
