### ISSUE TITLE
[ 7.6.x ] FAL default mount point set to the extension path

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FluidTYPO3/site#23]
Hi,

I've found that after a clean setup of Typo3 with this extension, the default mount point for FAL was set inside the extension that is created through the setup wizard.

I don't really know where this came from, but actually I had to set it up again to `fileadmin/` in the backend to get it working as usual.

For more details see https://github.com/FluidTYPO3/flux/issues/1044

**Comment by NamelessCoder** [comment]
Hey Julian,

Have you identified what aspects of the storage record we create that cause it to become the default? I'm unable to reproduce this one.

**Comment by julianxhokaxhiu** [comment]
I didn't had the occasion to kickstart a new Typo3 istance so unfortunatelly no. But when I'll do I'll give you some feedback ASAP!

**Comment by NamelessCoder** [comment]
Closing this one due to inactivity (which is perfectly okay, of course!) - I can only guess, but it appears the only way to cause the created FAL storage to become the default is to delete or disable the existing one, or of course switching the secondary one to default manually. The SQL that writes the storage record will definitely write it as "not default" ;)

If you do track this down to some bad behavior in the "site" extension I'm happy to reopen this issue (just let me know) but so far nobody seems to have trouble with this either before or after this one report. Should be a one-time problem.
