### ISSUE TITLE
[ 6.2.14 ] Internal Server Error

### ISSUE THREAD

**Issue by julianxhokaxhiu** [FluidTYPO3/site#9]
This is what I get from Logs after using the `Configure` button, typing my extension name, checking everything and pressing the `Submit` button.

```
PHP message: PHP Fatal error:  Call to a member function set() on null in /var/www/projectname/htdocs/typo3_src-6.2.14/typo3/sysext/core/Classes/Core/ClassAliasMap.php on line 141
```

On 6.2.13 I didn't had this issue before.

**Comment by NamelessCoder** [comment]
Core error; caused by the composer class loading having created temporary files that you must clear. We've made the provider extension that gets generated clear the system cache when it gets installed - if the problem persists, please report to the TYPO3 bug tracker.

Fix for `builder` will be on TER shortly. Retrying this again in a few days should let you perform the install without problems.
